// <auto-generated />
using System;
using KSimple.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KSimple.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200409050146_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("KSimple.Models.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("KSimple.Models.Entities.Packet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ServerTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserTimestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.ToTable("Packets");
                });

            modelBuilder.Entity("KSimple.Models.Entities.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDefinedId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasAlternateKey("UserDefinedId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("KSimple.Models.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelTree")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDefinedId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("UserDefinedId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("KSimple.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KSimple.Models.Misc.StorageGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "StorageId");

                    b.HasIndex("StorageId");

                    b.ToTable("StorageGroups");
                });

            modelBuilder.Entity("KSimple.Models.Misc.TemplateGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "TemplateId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateGroups");
                });

            modelBuilder.Entity("KSimple.Models.Misc.UserGroupRight", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupRights");
                });

            modelBuilder.Entity("KSimple.Models.Entities.Packet", b =>
                {
                    b.HasOne("KSimple.Models.Entities.Storage", null)
                        .WithMany("Packets")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSimple.Models.Entities.Storage", b =>
                {
                    b.HasOne("KSimple.Models.Entities.Template", "Template")
                        .WithMany("Storages")
                        .HasForeignKey("TemplateId");
                });

            modelBuilder.Entity("KSimple.Models.Misc.StorageGroup", b =>
                {
                    b.HasOne("KSimple.Models.Entities.Group", "Group")
                        .WithMany("StorageGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KSimple.Models.Entities.Storage", "Storage")
                        .WithMany("StorageGroups")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSimple.Models.Misc.TemplateGroup", b =>
                {
                    b.HasOne("KSimple.Models.Entities.Group", "Group")
                        .WithMany("TemplateGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KSimple.Models.Entities.Template", "Template")
                        .WithMany("TemplateGroups")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSimple.Models.Misc.UserGroupRight", b =>
                {
                    b.HasOne("KSimple.Models.Entities.Group", "Group")
                        .WithMany("UserGroupRights")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KSimple.Models.Entities.User", "User")
                        .WithMany("UserGroupRights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KSimple.Models.Misc.Right", "Rights", b1 =>
                        {
                            b1.Property<Guid>("UserGroupRightGroupId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserGroupRightUserId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("CanModifyStorages")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("CanReadStorages")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserGroupRightGroupId", "UserGroupRightUserId");

                            b1.ToTable("UserGroupRights");

                            b1.WithOwner()
                                .HasForeignKey("UserGroupRightGroupId", "UserGroupRightUserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
